## Tensors

In [ ]:
import tensorflow as tf


In [11]:
#Tensorflow constants
Scalar = tf.constant([2])
Vector = tf.constant([5,6,2])
Matrix = tf.constant([[1,2,3],[4,5,6],[7,8,9]])
Tensor = tf.constant([
    [[1,2,3],[2,3,4],[3,4,5]],
     [[1,2,3],[2,3,4],[3,4,5]],
     [[1,2,3],[2,3,4],[3,4,5]]
])

In [12]:
import numpy as np
 
#tensors using numpy
np_t_0 = np.array(10, dtype=np.int32)
np_t_1 = np.array([b"blue",b"red",b"green"])
np_t_2 = np.array([
[True,True,False],[False,False,True],[False,True,False]],dtype=np.bool)
 
Scalar_np = tf.constant(np_t_0)
Vector_np = tf.constant(np_t_1)
Matrix_np = tf.constant(np_t_2)

In [13]:
with tf.Session() as session:
    result = session.run(Scalar)
    print "Scalar (1 entry):\n %s \n" % result
    result = session.run(Vector)
    print "Vector (3 entries) :\n %s \n" % result
    result = session.run(Matrix)
    print "Matrix (3x3 entries):\n %s \n" % result
    result = session.run(Tensor)
    print "Tensor (3x3x3 entries) :\n %s \n" % result
    
    result = session.run(Scalar_np)
    print "Scalar (1 entry):\n %s \n" % result
    result = session.run(Vector_np)
    print "Vector (3 entries) :\n %s \n" % result
    result = session.run(Matrix_np)
    print "Matrix (3x3 entries):\n %s \n" % result

Scalar (1 entry):
 [2] 

Vector (3 entries) :
 [5 6 2] 

Matrix (3x3 entries):
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

Tensor (3x3x3 entries) :
 [[[1 2 3]
  [2 3 4]
  [3 4 5]]

 [[1 2 3]
  [2 3 4]
  [3 4 5]]

 [[1 2 3]
  [2 3 4]
  [3 4 5]]] 

Scalar (1 entry):
 10 

Vector (3 entries) :
 ['blue' 'red' 'green'] 

Matrix (3x3 entries):
 [[ True  True False]
 [False False  True]
 [False  True False]] 



## Run V Eval

In [14]:
# Using `Session.run()`.
sess = tf.Session()
c = tf.constant(5.0)
print(sess.run(c))
 
# Using `Tensor.eval()`.
c = tf.constant(5.0)
with tf.Session():
  print(c.eval())

5.0
5.0
