## Variables

We use variables to store data during computation.

In [31]:
import tensorflow as tf

In [32]:
#Different Tensor Variables

# Basic
y = tf.Variable(10, name='y')

#array
array = tf.Variable([1,2,3,4], name='array')
                
# Zeros
zeros=tf.zeros([3,2])

# Ones
ones = tf.ones([3,2])

# Random uniform values
rand_uniform = tf.random_uniform([3,2], minval = -10, maxval=10)

# Normally distributed numbers
rand_normal = tf.random_normal([3,2],mean=0.0,stddev=3.0)

In [33]:
#Changing values of variables
my_variable = tf.Variable(0)

increment_my_variable = my_variable.assign(my_variable + 1)

In [34]:
# Add an op to initialize the variables.
init_op = tf.global_variables_initializer()

In [35]:
#execute with examples
session = tf.Session()
session.run(init_op)


In [36]:
print(session.run(y))

10


In [37]:
print(session.run(array))

[1 2 3 4]


In [38]:
print(session.run(zeros))

[[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]]


In [39]:
print(session.run(ones))

[[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]]


In [40]:
print(session.run(rand_uniform))

[[ 7.72863579 -4.7578001 ]
 [ 2.58307934 -2.22212315]
 [-4.56864834 -1.49850845]]


In [41]:
print(session.run(rand_normal))

[[ 1.76291156 -0.15611187]
 [-1.22322226  4.00286293]
 [-3.7710557   5.20210314]]


In [42]:
print(session.run(increment_my_variable))
print(session.run(increment_my_variable))
print(session.run(increment_my_variable))
print(session.run(increment_my_variable))

session.run(my_variable.assign(0))

print(session.run(increment_my_variable))
print(session.run(increment_my_variable))

1
2
3
4
1
2


In [43]:
# Use this operation to save the session variables
saver = tf.train.Saver()

# Run the save operation
save_path = saver.save(session, "./model.ckpt")
print("Saved: %s" % save_path)

Saved: ./model.ckpt


In [44]:
#This will be the same as the Saved value in model.ckpt
print("Current Value: " , session.run(my_variable))

# Change the value
print("Changed Value:", session.run(my_variable.assign(0)))

# Restore value from file
saver.restore(session, "./model.ckpt")

# Value has been restored
print("Restored Value From File:",session.run(my_variable))

('Current Value: ', 2)
('Changed Value:', 0)
('Restored Value From File:', 2)


In [45]:
session.close()